---
- name: Install Tailscale and start service
  become: yes
  
    - name: Add Tailscale APT repository key
      apt_key:
        url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ubuntu_version }}.noarmor.gpg"
        state: present

    - name: Add Tailscale APT repository
      apt_repository:
        repo: "deb https://pkgs.tailscale.com/stable/ubuntu {{ ubuntu_version }} main"
        state: present

    - name: Install Tailscale
      apt:
        name: tailscale
        state: present

    - name: Start and enable Tailscale service
      systemd:
        name: tailscaled
        state: started
        enabled: yes
      register: tailscale_output

    - name: Install | Check if Tailscale is connected
      ansible.builtin.command: tailscale status
      changed_when: false
      register: tailscale_status
      failed_when:
        - tailscale_status.rc != 0
        - "'Logged out.' not in tailscale_status.stdout"
        - "'not logged in' not in tailscale_status.stdout"


    - name: Install | Bring Tailscale Up
      become: true
      ansible.builtin.command: "tailscale up --authkey={ tailscale_authkey }"
      register: tailscale_start
      async: 60
      poll: 5